/// Flutter icons MyFlutterIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterIcons
///      fonts:
///       - asset: fonts/MyFlutterIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterIcons {
  MyFlutterIcons._();

  static const _kFontFam = 'MyFlutterIcons';
  static const _kFontPkg = null;

  static const IconData adidas = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
